-- Generated by Tools\update-images.ps1: the pictures in this folder, for the Visual note menu.
-- WoW reads this file at start, like the pictures: restart WoW after adding pictures.
local _, SRT = ...
SRT.ImageList = {
    "test_shot",
    "wailing_caverns",
}
