# update-images.ps1 - rebuild Images\list.lua, the list of pictures ART shows in the
# Visual note "Picture" menu (an addon cannot list a folder by itself).
# img2tga.ps1 runs this for you; run it yourself after copying .tga/.blp files into Images.
# Usage: powershell -ExecutionPolicy Bypass -File update-images.ps1
$dir = Join-Path (Split-Path -Parent $PSScriptRoot) "Images"
$names = Get-ChildItem -Path $dir -File |
    Where-Object { $_.Extension -in ".tga", ".blp" } |
    ForEach-Object { $_.BaseName.ToLower() } |
    Where-Object { $_ -match '^[a-z0-9_-]+$' } |
    Sort-Object -Unique
$lines = @(
    "-- Generated by Tools\update-images.ps1: the pictures in this folder, for the Visual note menu.",
    "-- WoW reads this file at start, like the pictures: restart WoW after adding pictures.",
    "local _, ART = ...",
    "ART.ImageList = {"
)
foreach ($n in $names) { $lines += ('    "{0}",' -f $n) }
$lines += "}"
$out = Join-Path $dir "list.lua"
[System.IO.File]::WriteAllLines($out, $lines)
"Images\list.lua: {0} picture(s): {1}" -f @($names).Count, ($names -join ", ")
